In [1]:
import pandas as pd

In [3]:
d = pd.read_csv("zim_test.csv")
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [4]:
d[d.isnull().any(axis = 1)]

     Duration  Pulse  Maxpulse  Calories
17         45     90       112       NaN
27         60    103       132       NaN
91         45    107       137       NaN
118        60    105       125       NaN
141        60     97       127       NaN

In [7]:
# add------remove
# add -------fillna()
d.fillna(100, inplace = True)

In [8]:
d["Calories"][91]

np.float64(100.0)

In [16]:
d[d.isnull().any(axis = 1)]

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

In [17]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [10]:
# remove -----dropna()
dd = pd.read_csv("zim_test(1).csv")
dd

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1         600    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166       600    115       145     310.2
167        75    120       150     320.4
168       750    125       150     330.4

[169 rows x 4 columns]

In [11]:
dd[dd.isnull().any(axis = 1)]

     Duration  Pulse  Maxpulse  Calories
17         45     90       112       NaN
27         60    103       132       NaN
91         45    107       137       NaN
118        60    105       125       NaN
141        60     97       127       NaN

In [13]:
dd.dropna(inplace = True)

In [14]:
dd[dd.isnull().any(axis = 1)]

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

In [15]:
dd.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  164 non-null    int64
 1   Pulse     164 non-null    int64
 2   Maxpulse  164 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB

In [18]:
dd[dd.duplicated()]

     Duration  Pulse  Maxpulse  Calories
36         60    102       127     300.0
38         60    100       120     300.0
40         45     90       112     180.1
71         60    109       153     387.6
113        45    100       120     225.3
155        60    111       151     368.5

In [19]:
dd.drop_duplicates(inplace = True)