# PANDAS

data structers
1) Series
2) DataFrame

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\ishat\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ishat\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ishat\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ishat\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ishat\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\ishat\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

In [8]:
a = pd.Series([2,4,5,67,9])
print(type(a))
print(a[3])
a

<class 'pandas.core.series.Series'>
67

0     2
1     4
2     5
3    67
4     9
dtype: int64

In [18]:
a = pd.DataFrame(
    {
        "name": ["a","d","x"],
        "age": [2,3,4],
        "id":[22,33,44]
    }
)
print(type(a))
print(a["name"])
print(a["id"][1])
a

<class 'pandas.core.frame.DataFrame'>
0    a
1    d
2    x
Name: name, dtype: object
33

  name  age  id
0    a    2  22
1    d    3  33
2    x    4  44

In [22]:
aa = pd.read_csv("C:\\Users\\ishat\\Downloads\\archive\\police.csv")
aa

,stop_date,stop_time,county_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,2005-01-02,01:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,2005-01-18,08:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,2005-01-23,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2005-02-20,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,2005-03-14,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91736,2015-12-31,20:27,NaN,M,1986.0,29.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
91737,2015-12-31,20:35,NaN,F,1982.0,33.0,White,Equipment/Inspection Violation,Equipment,False,NaN,Warning,False,0-15 Min,False
91738,2015-12-31,20:45,NaN,M,1992.0,23.0,White,Other Traffic Violation,Moving violation,False,NaN,Warning,False,0-15 Min,False
91739,2015-12-31,21:42,NaN,M,1993.0,22.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
91740,2015-12-31,22:46,NaN,M,1959.0,56.0,Hispanic,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [23]:
x = pd.read_csv("zim_test.csv")
x

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1         600    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166       600    115       145     310.2
167        75    120       150     320.4
168       750    125       150     330.4

[169 rows x 4 columns]

In [24]:
x.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1       600    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [25]:
x.head(10)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1       600    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7       450    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0

In [26]:
x.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166       600    115       145     310.2
167        75    120       150     320.4
168       750    125       150     330.4

In [27]:
x.tail(8)

     Duration  Pulse  Maxpulse  Calories
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166       600    115       145     310.2
167        75    120       150     320.4
168       750    125       150     330.4

In [29]:
x.sample()

     Duration  Pulse  Maxpulse  Calories
145        45    106       126     270.8

In [32]:
x.sample(3)

     Duration  Pulse  Maxpulse  Calories
78        120    100       130     500.4
167        75    120       150     320.4
164        60    105       140     290.8

In [33]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [34]:
x.describe()

          Duration       Pulse    Maxpulse     Calories
count   169.000000  169.000000  169.000000   164.000000
mean     92.603550  106.828402  134.047337   375.790244
std     144.444841   16.699733   16.450434   266.379919
min      15.000000    0.000000  100.000000    50.300000
25%      45.000000  100.000000  124.000000   250.925000
50%      60.000000  105.000000  131.000000   318.600000
75%      60.000000  111.000000  141.000000   387.600000
max    1200.000000  159.000000  184.000000  1860.400000

In [35]:
x["Duration"]

0       60
1      600
2       60
3       45
4       45
      ...
164     60
165     60
166    600
167     75
168    750
Name: Duration, Length: 169, dtype: int64

In [36]:
x["Pulse"][9]

np.int64(98)

In [37]:
# loc 

x.loc[3]

Duration     45.0
Pulse       109.0
Maxpulse    175.0
Calories    282.4
Name: 3, dtype: float64

In [38]:
x.iloc[10:21,0:3]

    Duration  Pulse  Maxpulse
10        60    103       147
11        60    100       120
12        60    106       128
13        60    104       132
14        60     98       123
15        60     98       120
16       600    100       120
17        45     90       112
18        60    103       123
19        45     97       125
20        60    108       131

In [39]:
x.iloc[0:11,:]

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1        600    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7        450    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3

In [40]:
x.iloc[:,0:2]

     Duration  Pulse
0          60    110
1         600    117
2          60    103
3          45    109
4          45    117
..        ...    ...
164        60    105
165        60    110
166       600    115
167        75    120
168       750    125

[169 rows x 2 columns]